services:
  - type: web
    name: traffic-management-system
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT traffic:app
    healthCheckPath: /healthz
